### ISSUE TITLE
Problem Generator-jhipster-bootstrap-material-design

### ISSUE THREAD

**Issue by moifort** [moifort/generator-jhipster-bootstrap-material-design#1]
I try to install your but when i do `yo jhipster-bootstrap-material-design` i have this error : 

```bash
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the JHipster |
   `---------´   |    Bootstrap Material    |
    ( _´U`_ )    |     design generator!    |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Do you want to install Bootstrap Material design? Yes
Composing JHipster configuration with module bootstrap-material-design
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addBowerDependency is not a function
    at module.exports.yeoman.generators.Base.extend.writing (MyUSer\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:62:22)
    at MyUSer\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by moifort** [comment]
To run the generator you need to have a JHipster application generate by 2.26.0 JHipster version or older.

**Comment by NathanAK** [comment]
I still get this error no matter what version I use.

**Comment by robertolos** [comment]
Hi I'm getting the same error with jhipster 3.0

**Comment by amirensit** [comment]
same problem  !
