### ISSUE TITLE
Material Design not working on heroku

### ISSUE THREAD

**Issue by ihrigb** [moifort/generator-jhipster-bootstrap-material-design#17]
I generated a blank JHipster app, run the jhipster-bootstrap-material-design generator on it and deployed to heroku. Now UI does not render with following exception:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module proBandApp due to:
Error: [$injector:unpr] Unknown provider: DEBUG_INFO_ENABLED
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=DEBUG_INFO_ENABLED
```

Locally it works.

**Comment by jakemonO** [comment]
tried to install into existing jhipster 4.03 project with angular2 and get this:
```
Composing JHipster configuration with module bootstrap-material-design
Reading the JHipster project configuration for your module
TypeError: Cannot set property 'arrive' of undefined
    at C:\myproject\node_modules\generator-jhipster\generators\generator-base.js:405:40
    at Object.rewriteJSONFile (C:\myproject\node_modules\generator-jhipster\generators\util.js:92:5)
    at Object.Generator.addBowerDependency (C:\myproject\node_modules\generator-jhipster\generators\generator-base.js:404:23)
    at child.writing (C:\Users\me\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:66:22)
    at C:\Users\me\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

Unable to find bower.json. Reference to bower dependency (name: arrive, version:2.3.0) not added.
```
I installed bower and initialized it in the project so there's a basec (empty, pretty much) bower.json in the project root.

**Comment by AbyJacob** [comment]
Facing the same issue while making the prod build , any resolutions ? 
Error: [$injector:unpr] Unknown provider: DEBUG_INFO_ENABLED

**Comment by ihrigb** [comment]
Well, this is a workaround, but surely not the solution to this. Unfortunately I am not very familiar with these  JS things. Would take me some time to dig into this... Maybe someone else is quicker.
