### ISSUE TITLE
To install Bootstrap-material design here is error

### ISSUE THREAD

**Issue by koyaja** [moifort/generator-jhipster-bootstrap-material-design#19]
? Do you want to install Bootstrap Material design? Yes
Composing JHipster configuration with module bootstrap-material-design
Reading the JHipster project configuration for your module
TypeError: Cannot read property 'dependencies' of undefined
    at C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\generator-base.js:407:20
    at Object.rewriteJSONFile (C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\util.js:92:5)
    at Object.Generator.addBowerDependency (C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\generator-base.js:406:23)
    at child.writing (C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:66:22)
    at C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

Unable to find bower.json. Reference to bower dependency (name: arrive, version:2.3.0) not added.

TypeError: Cannot read property 'dependencies' of undefined
    at C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\generator-base.js:407:20
    at Object.rewriteJSONFile (C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\util.js:92:5)
    at Object.Generator.addBowerDependency (C:\Personelle\Projet\JHipster\testgetway\node_modules\generator-jhipster\generators\generator-base.js:406:23)
    at child.writing (C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:67:22)
    at C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

Unable to find bower.json. Reference to bower dependency (name: bootstrap-material-design, version:0.5.10) not added.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Personelle\Projet\JHipster\testgetway\src\main\webapp\app\layouts\navbar\navbar.html'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at child.writing (C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:74:23)
    at C:\Users\M. KOMACLO\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

thanks for the help

**Comment by SLOBYYYY** [comment]
I'm still very new to JHipster and the new Angular, BUT:

You can get past this if you copy your package.json to bower.json. It will still whine about not finding navbar.html and I think it's because Angular 4 changed up the structure of it's js/html/scss files.
You can try and update `/node_modules/generator-jhipster-bootstrap-material-design/generators/app/index.js:74` to look for the proper navigation html. I tried that and I COULD get down 1 step but chose not to.
IMO the generator is not yet ready to work with the newest JHipster-Angular4 setup.

**Comment by amirensit** [comment]
I have the same problem.
Any idea please
